# Form implementation generated from reading ui file 'blue_line_page.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.blue_line_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.blue_line_label.setGeometry(QtCore.QRect(130, 50, 521, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.blue_line_label.setFont(font)
        self.blue_line_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.blue_line_label.setObjectName("blue_line_label")
        self.blue_line_pic = QtWidgets.QLabel(parent=self.centralwidget)
        self.blue_line_pic.setGeometry(QtCore.QRect(50, 120, 681, 251))
        self.blue_line_pic.setText("")
        self.blue_line_pic.setPixmap(QtGui.QPixmap("../assets/blue_line_layout.png"))
        self.blue_line_pic.setScaledContents(True)
        self.blue_line_pic.setObjectName("blue_line_pic")
        self.btn_tc1b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tc1b.setGeometry(QtCore.QRect(250, 260, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        self.btn_tc1b.setFont(font)
        self.btn_tc1b.setAutoFillBackground(True)
        self.btn_tc1b.setCheckable(False)
        self.btn_tc1b.setObjectName("btn_tc1b")
        self.btn_tc2b = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tc2b.setGeometry(QtCore.QRect(370, 150, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        self.btn_tc2b.setFont(font)
        self.btn_tc2b.setAutoFillBackground(True)
        self.btn_tc2b.setCheckable(False)
        self.btn_tc2b.setObjectName("btn_tc2b")
        self.btn_tc2b_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_tc2b_2.setGeometry(QtCore.QRect(530, 250, 100, 32))
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        self.btn_tc2b_2.setFont(font)
        self.btn_tc2b_2.setAutoFillBackground(True)
        self.btn_tc2b_2.setCheckable(False)
        self.btn_tc2b_2.setObjectName("btn_tc2b_2")
        self.back_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(340, 450, 100, 32))
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blue_line_label.setText(_translate("MainWindow", "You are viewing: Blue Line"))
        self.btn_tc1b.setText(_translate("MainWindow", "1B"))
        self.btn_tc2b.setText(_translate("MainWindow", "2B"))
        self.btn_tc2b_2.setText(_translate("MainWindow", "3B"))
        self.back_button.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
