

import_track(in line)

get_line_list()
get_section_list(in line)
get_number_list(in line, in section)
get_switch_list(in line)
get_switch_position_list(in line)
get_light_list(in line)
get_rail_crossing_list(in line)
break_thing(in failure, in line, in block)
fix_thing(in line, in block)
init_block_status()
init_switch_status()
init_light_status()
new_train_signal()
get_beacon_list()
set_track_heater(in temp)
get_passengers(in Train)
get_ticket_sales(in Train)
get_power_failure(in Train)
run()
init_crossing_status()
